---
name: Compile & push JSON schema to the Docs repository
description: Take a local YML schema file, dereference/bundle it & push it to zai-docs
inputs:
  schema_path:
    desc: Relative path to find the schema YML file, e.g. public/consumers/docs/procurement.yml
    required: true

  name:
    desc: Name of the resulting schema file, e.g. procurement_consumer
    required: true

  mode:
    desc: Whether to `dereference` (completely compile) or `bundle` (preserve internal $ref pointers) the schema
    default: dereference

  token:
    desc: GitHub token with write access to zaikio/zai-docs
    required: true

runs:
  using: composite
  steps:
    - name: Install dependencies (removes package.json if exists)
      shell: bash
      run: |-
        rm package.json
        npm install json-schema-ref-parser@9.0.9

    - name: Compile schema
      shell: bash
      run: |-
        echo "require('json-schema-ref-parser').${{ inputs.mode }}('${{ inputs.schema_path }}').then(s => process.stdout.write(JSON.stringify(s, null, 2)));" | node > ${{ inputs.name}}.json

    - name: Checkout zaikio/zai-docs repo
      uses: actions/checkout@v3
      with:
        repository: zaikio/zai-docs
        path: zai-docs
        token: ${{ inputs.token }}

    - name: Push to zaikio/zai-docs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        cp ${{ inputs.name }}.json zai-docs/
        cd zai-docs

        BRANCH=update-schemas-${{ inputs.name }}
        git checkout -b ${BRANCH}
        git add ${{ inputs.name }}.json

        git config user.name "Zaikio Bot"
        git config user.email dev@zaikio.com

        git commit -m "Update schema files from ${{ inputs.name }}"
        git push -f origin HEAD:${BRANCH}
